name: Build and publish

on:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Fetch info
      run: ./fetch_info.sh
      env:
        IMAGE_REPOSITORY: docker.pkg.github.com/f0rmiga/bazel-docker-image/bazel
        VERSION_FILE: version.txt

    - name: Docker login
      run: docker login --username thulioassis --password-stdin <<<"${DOCKERHUB_TOKEN}"
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: docker build --build-arg version="$(cat version.txt)" -t "thulioassis/bazel-docker-image/bazel:$(cat version.txt)" .

    - name: Publish
      run: docker push "thulioassis/bazel-docker-image/bazel:$(cat version.txt)"
