name: Build and publish

on:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Docker login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build
      uses: actions/docker/cli@master
      with:
        entrypoint: /bin/sh
        args: build.sh
      env:
        OUT: /tmp/image.txt

    - name: Publish
      uses: actions/docker/cli@master
      with:
        args: push $(cat /tmp/image.txt)
