name: Build and publish

on:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch info
      id: fetch_info
      run: |-
        set -o errexit -o nounset
        latest_bazel_url="https://api.github.com/repos/bazelbuild/bazel/releases/latest"
        version=$(curl --fail --silent --show-error "${latest_bazel_url}" | awk 'match($0, /"tag_name": "(.*)"/, cg) { print cg[1] }')
        echo "::set-output name=version::${version}"
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_REGISTRY_PASSWORD }}
        registry: https://ghcr.io
        repository: ${{ github.repository_owner }}/bazel
        tags: >-
          ${{ steps.fetch_info.outputs.version }}
        build_args: >-
          version=${{ steps.fetch_info.outputs.version }}
        labels: >-
          org.opencontainers.image.version=${{ steps.fetch_info.outputs.version }}
        add_git_labels: true
        always_pull: true
