name: Build and publish

on:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Fetch info
      run: ./fetch_info.sh
      env:
        IMAGE_REPOSITORY: docker.pkg.github.com/f0rmiga/bazel-docker-image/bazel
        VERSION_FILE: version.txt

    - name: Docker login
      run: docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}

    - name: Build
      run: docker build --build-arg version="$(cat version)" -t "docker.pkg.github.com/f0rmiga/bazel-docker-image/bazel:$(cat version.txt)" .

    - name: Publish
      run: docker push "docker.pkg.github.com/f0rmiga/bazel-docker-image/bazel:$(cat version.txt)"
