name: Build and publish

on:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * *

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Fetch info
      run: ./fetch_info.sh
      env:
        VERSION_FILE: version
        IMAGE_FILE: image

    - name: Docker login
      run: docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}

    - name: Build
      run: docker build --build-arg version="$(cat version)" -t "$(cat image)" .

    - name: Publish
      run: docker push "$(cat image)"
